[tool.poetry]
name = "learndask"
version = "0.1.0"
description = "learn Dask"
authors = ["vitahoang"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
dask = "^2024.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
